import { EnemyDefinition, EnemyType } from '../types/game.types'

export const ENEMY_DEFINITIONS: Record<EnemyType, EnemyDefinition> = {
  time_construct_basic: {
    type: 'time_construct_basic',
    name: '时砂构造体·基础',
    hp: 80,
    speed: 80,
    damage: 15,
    aggroRange: 250,
    attackRange: 80,
    attackCooldown: 1200,
    spriteKey: 'enemy_basic',
    isBoss: false,
    dropTable: [
      { itemType: 'time_sand', amount: 10, chance: 1.0 },
      { itemType: 'skill_memory', chance: 0.05 },
    ],
  },
  time_construct_heavy: {
    type: 'time_construct_heavy',
    name: '时砂构造体·重型',
    hp: 250,
    speed: 45,
    damage: 35,
    aggroRange: 200,
    attackRange: 100,
    attackCooldown: 2000,
    spriteKey: 'enemy_heavy',
    isBoss: false,
    dropTable: [
      { itemType: 'time_sand', amount: 30, chance: 1.0 },
      { itemType: 'module', chance: 0.15 },
      { itemType: 'skill_memory', chance: 0.1 },
    ],
  },
  void_drone: {
    type: 'void_drone',
    name: '虚空无人机',
    hp: 40,
    speed: 140,
    damage: 12,
    aggroRange: 350,
    attackRange: 200,
    attackCooldown: 800,
    spriteKey: 'enemy_drone',
    isBoss: false,
    dropTable: [
      { itemType: 'time_sand', amount: 8, chance: 1.0 },
    ],
  },
  echo_hunter: {
    type: 'echo_hunter',
    name: '回响猎手',
    hp: 150,
    speed: 100,
    damage: 28,
    aggroRange: 300,
    attackRange: 150,
    attackCooldown: 1500,
    spriteKey: 'enemy_hunter',
    isBoss: false,
    dropTable: [
      { itemType: 'time_sand', amount: 25, chance: 1.0 },
      { itemType: 'crystal', chance: 0.2 },
    ],
  },
  time_wraith: {
    type: 'time_wraith',
    name: '时间幽灵',
    hp: 90,
    speed: 110,
    damage: 20,
    aggroRange: 280,
    attackRange: 120,
    attackCooldown: 1000,
    spriteKey: 'enemy_wraith',
    isBoss: false,
    dropTable: [
      { itemType: 'time_sand', amount: 15, chance: 1.0 },
      { itemType: 'crystal', chance: 0.3 },
    ],
  },
  ancient_guardian: {
    type: 'ancient_guardian',
    name: '上古守护者',
    hp: 2000,
    speed: 55,
    damage: 60,
    aggroRange: 400,
    attackRange: 200,
    attackCooldown: 2500,
    spriteKey: 'enemy_boss',
    isBoss: true,
    dropTable: [
      { itemType: 'time_sand', amount: 300, chance: 1.0 },
      { itemType: 'crystal', chance: 1.0 },
      { itemType: 'module', chance: 0.8 },
    ],
  },
  void_sniper: {
    type: 'void_sniper',
    name: '虚空狙击手',
    hp: 70,
    speed: 65,
    damage: 28,
    aggroRange: 520,
    attackRange: 480,
    attackCooldown: 2800,
    spriteKey: 'enemy_sniper',
    isBoss: false,
    dropTable: [
      { itemType: 'time_sand', amount: 20, chance: 1.0 },
      { itemType: 'module', chance: 0.1 },
    ],
  },
}
