// AUTO-GENERATED by tools/generate_puzzle_levels.py — DO NOT EDIT MANUALLY
// Seed: 2026 | 30 solo levels + 5 co-op levels

export interface PuzzlePad {
  id: string
  x: number
  y: number
  color: string
}

export interface PuzzleDoor {
  x: number
  y: number
  w: number
  h: number
  requiredPads: string[]
  windowMs: number
}

export interface PuzzleLevel {
  id: number
  name: string
  hint: string
  solution: string
  pads: PuzzlePad[]
  doors: PuzzleDoor[]
  exitX: number
  exitY: number
  coop: boolean
  sandReward: number
}

export const PUZZLE_LEVELS: readonly PuzzleLevel[] = [
  {
    id: 1,
    name: '第1室·共鸣',
    hint: '踩 A（记住），走向 B 踩下——回响同时触发 A，两者在 2000ms 内激活开门',
    solution: 'A → B（回响 A）→ 门开',
    pads: [
      { id: 'A', x: 196, y: 218, color: '#50e8a0' },
      { id: 'B', x: 589, y: 317, color: '#e0a030' },
    ],
    doors: [
      { x: 900, y: 310, w: 55, h: 160, requiredPads: ['A', 'B'], windowMs: 2000 },
    ],
    exitX: 938,
    exitY: 310,
    coop: false,
    sandReward: 18,
  },
  {
    id: 2,
    name: '第2室·共鸣',
    hint: '踩 A（记住），走向 B 踩下——回响同时触发 A，两者在 1900ms 内激活开门',
    solution: 'A → B（回响 A）→ 门开',
    pads: [
      { id: 'A', x: 180, y: 169, color: '#50e8a0' },
      { id: 'B', x: 690, y: 373, color: '#e0a030' },
    ],
    doors: [
      { x: 900, y: 310, w: 55, h: 160, requiredPads: ['A', 'B'], windowMs: 1900 },
    ],
    exitX: 938,
    exitY: 310,
    coop: false,
    sandReward: 21,
  },
  {
    id: 3,
    name: '第3室·共鸣',
    hint: '踩 A（记住），走向 B 踩下——回响同时触发 A，两者在 1800ms 内激活开门',
    solution: 'A → B（回响 A）→ 门开',
    pads: [
      { id: 'A', x: 505, y: 456, color: '#50e8a0' },
      { id: 'B', x: 661, y: 335, color: '#e0a030' },
    ],
    doors: [
      { x: 900, y: 310, w: 55, h: 160, requiredPads: ['A', 'B'], windowMs: 1800 },
    ],
    exitX: 938,
    exitY: 310,
    coop: false,
    sandReward: 24,
  },
  {
    id: 4,
    name: '第4室·共鸣',
    hint: '踩 A（记住），走向 B 踩下——回响同时触发 A，两者在 1700ms 内激活开门',
    solution: 'A → B（回响 A）→ 门开',
    pads: [
      { id: 'A', x: 577, y: 439, color: '#50e8a0' },
      { id: 'B', x: 675, y: 280, color: '#e0a030' },
    ],
    doors: [
      { x: 900, y: 220, w: 55, h: 160, requiredPads: ['A', 'B'], windowMs: 1700 },
    ],
    exitX: 938,
    exitY: 220,
    coop: false,
    sandReward: 27,
  },
  {
    id: 5,
    name: '第5室·共鸣',
    hint: '踩 A（记住），走向 B 踩下——回响同时触发 A，两者在 1600ms 内激活开门',
    solution: 'A → B（回响 A）→ 门开',
    pads: [
      { id: 'A', x: 77, y: 369, color: '#50e8a0' },
      { id: 'B', x: 157, y: 111, color: '#e0a030' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'B'], windowMs: 1600 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 30,
  },
  {
    id: 6,
    name: '第6室·双响',
    hint: `门需要 A 激活两次（间隔 ≤ 1800ms）
踩 A（记住），快速走向 B 踩下——回响再次触发 A`,
    solution: 'A → B（回响 A → A 第二次激活）→ 门开',
    pads: [
      { id: 'A', x: 175, y: 285, color: '#50e8a0' },
      { id: 'B', x: 86, y: 472, color: '#e0a030' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'A'], windowMs: 1800 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 33,
  },
  {
    id: 7,
    name: '第7室·双响',
    hint: `门需要 A 激活两次（间隔 ≤ 1600ms）
踩 A（记住），快速走向 B 踩下——回响再次触发 A`,
    solution: 'A → B（回响 A → A 第二次激活）→ 门开',
    pads: [
      { id: 'A', x: 776, y: 306, color: '#50e8a0' },
      { id: 'B', x: 770, y: 215, color: '#e0a030' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'A'], windowMs: 1600 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 37,
  },
  {
    id: 8,
    name: '第8室·双响',
    hint: `门需要 A 激活两次（间隔 ≤ 1450ms）
踩 A（记住），快速走向 B 踩下——回响再次触发 A`,
    solution: 'A → B（回响 A → A 第二次激活）→ 门开',
    pads: [
      { id: 'A', x: 290, y: 258, color: '#50e8a0' },
      { id: 'B', x: 440, y: 467, color: '#e0a030' },
      { id: 'C', x: 600, y: 381, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'A'], windowMs: 1450 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 41,
  },
  {
    id: 9,
    name: '第9室·双响',
    hint: `门需要 A 激活两次（间隔 ≤ 1300ms）
踩 A（记住），快速走向 B 踩下——回响再次触发 A`,
    solution: 'A → B（回响 A → A 第二次激活）→ 门开',
    pads: [
      { id: 'A', x: 153, y: 425, color: '#50e8a0' },
      { id: 'B', x: 194, y: 272, color: '#e0a030' },
      { id: 'C', x: 593, y: 465, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'A'], windowMs: 1300 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 45,
  },
  {
    id: 10,
    name: '第10室·双响',
    hint: `门需要 A 激活两次（间隔 ≤ 1150ms）
踩 A（记住），快速走向 B 踩下——回响再次触发 A`,
    solution: 'A → B（回响 A → A 第二次激活）→ 门开',
    pads: [
      { id: 'A', x: 689, y: 306, color: '#50e8a0' },
      { id: 'B', x: 505, y: 343, color: '#e0a030' },
      { id: 'C', x: 605, y: 467, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'A'], windowMs: 1150 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 49,
  },
  {
    id: 11,
    name: '第11室·三鸣',
    hint: `门需要 A 和 C（1600ms 内）
直接来回走不到，注意：踩了 B 会打断回响链
先踩 C（记住），再踩 A——回响触发 C`,
    solution: 'C → A（回响 C，A+C 同步激活）→ 门开（避开 B）',
    pads: [
      { id: 'A', x: 100, y: 349, color: '#50e8a0' },
      { id: 'C', x: 304, y: 447, color: '#c060ff' },
      { id: 'C', x: 155, y: 442, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'C'], windowMs: 1600 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 52,
  },
  {
    id: 12,
    name: '第12室·三鸣',
    hint: `门需要 A 和 C（1450ms 内）
直接来回走不到，注意：踩了 B 会打断回响链
先踩 C（记住），再踩 A——回响触发 C`,
    solution: 'C → A（回响 C，A+C 同步激活）→ 门开（避开 B）',
    pads: [
      { id: 'A', x: 125, y: 415, color: '#50e8a0' },
      { id: 'C', x: 610, y: 398, color: '#c060ff' },
      { id: 'C', x: 313, y: 437, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'C'], windowMs: 1450 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 56,
  },
  {
    id: 13,
    name: '第13室·三鸣',
    hint: `门需要 A 和 C（1300ms 内）
直接来回走不到，注意：踩了 B 会打断回响链
先踩 C（记住），再踩 A——回响触发 C`,
    solution: 'C → A（回响 C，A+C 同步激活）→ 门开（避开 B）',
    pads: [
      { id: 'A', x: 712, y: 274, color: '#50e8a0' },
      { id: 'C', x: 556, y: 127, color: '#c060ff' },
      { id: 'C', x: 309, y: 490, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'C'], windowMs: 1300 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 60,
  },
  {
    id: 14,
    name: '第14室·三鸣',
    hint: `门需要 A 和 C（1150ms 内）
直接来回走不到，注意：踩了 B 会打断回响链
先踩 C（记住），再踩 A——回响触发 C`,
    solution: 'C → A（回响 C，A+C 同步激活）→ 门开（避开 B）',
    pads: [
      { id: 'A', x: 199, y: 375, color: '#50e8a0' },
      { id: 'C', x: 792, y: 288, color: '#c060ff' },
      { id: 'C', x: 535, y: 362, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'C'], windowMs: 1150 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 64,
  },
  {
    id: 15,
    name: '第15室·三鸣',
    hint: `门需要 A 和 C（1000ms 内）
直接来回走不到，注意：踩了 B 会打断回响链
先踩 C（记住），再踩 A——回响触发 C`,
    solution: 'C → A（回响 C，A+C 同步激活）→ 门开（避开 B）',
    pads: [
      { id: 'A', x: 633, y: 183, color: '#50e8a0' },
      { id: 'C', x: 760, y: 212, color: '#c060ff' },
      { id: 'C', x: 737, y: 311, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'C'], windowMs: 1000 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 68,
  },
  {
    id: 16,
    name: '第16室·双门',
    hint: `两扇门都要打开（各需在 1800ms 内满足）
门1需要 A+B，门2需要 B+C
利用 B 作为枢纽：A→B（回响A）→C（回响B）`,
    solution: 'A → B（回响A，门1开）→ C（回响B，门2开）→ 通过',
    pads: [
      { id: 'A', x: 790, y: 300, color: '#50e8a0' },
      { id: 'B', x: 486, y: 276, color: '#e0a030' },
      { id: 'C', x: 282, y: 205, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 205, w: 55, h: 108, requiredPads: ['A', 'B'], windowMs: 1800 },
      { x: 900, y: 350, w: 55, h: 108, requiredPads: ['B', 'C'], windowMs: 1800 },
    ],
    exitX: 938,
    exitY: 278,
    coop: false,
    sandReward: 72,
  },
  {
    id: 17,
    name: '第17室·双门',
    hint: `两扇门都要打开（各需在 1650ms 内满足）
门1需要 A+B，门2需要 B+C
利用 B 作为枢纽：A→B（回响A）→C（回响B）`,
    solution: 'A → B（回响A，门1开）→ C（回响B，门2开）→ 通过',
    pads: [
      { id: 'A', x: 350, y: 59, color: '#50e8a0' },
      { id: 'B', x: 108, y: 131, color: '#e0a030' },
      { id: 'C', x: 746, y: 360, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 205, w: 55, h: 108, requiredPads: ['A', 'B'], windowMs: 1650 },
      { x: 900, y: 350, w: 55, h: 108, requiredPads: ['B', 'C'], windowMs: 1650 },
    ],
    exitX: 938,
    exitY: 278,
    coop: false,
    sandReward: 77,
  },
  {
    id: 18,
    name: '第18室·双门',
    hint: `两扇门都要打开（各需在 1500ms 内满足）
门1需要 A+B，门2需要 B+C
利用 B 作为枢纽：A→B（回响A）→C（回响B）`,
    solution: 'A → B（回响A，门1开）→ C（回响B，门2开）→ 通过',
    pads: [
      { id: 'A', x: 544, y: 466, color: '#50e8a0' },
      { id: 'B', x: 610, y: 305, color: '#e0a030' },
      { id: 'C', x: 443, y: 157, color: '#c060ff' },
      { id: 'D', x: 341, y: 409, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 205, w: 55, h: 108, requiredPads: ['A', 'B'], windowMs: 1500 },
      { x: 900, y: 350, w: 55, h: 108, requiredPads: ['B', 'C'], windowMs: 1500 },
    ],
    exitX: 938,
    exitY: 278,
    coop: false,
    sandReward: 82,
  },
  {
    id: 19,
    name: '第19室·双门',
    hint: `两扇门都要打开（各需在 1350ms 内满足）
门1需要 A+B，门2需要 B+C
利用 B 作为枢纽：A→B（回响A）→C（回响B）`,
    solution: 'A → B（回响A，门1开）→ C（回响B，门2开）→ 通过',
    pads: [
      { id: 'A', x: 572, y: 293, color: '#50e8a0' },
      { id: 'B', x: 598, y: 447, color: '#e0a030' },
      { id: 'C', x: 754, y: 72, color: '#c060ff' },
      { id: 'D', x: 372, y: 217, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 205, w: 55, h: 108, requiredPads: ['A', 'B'], windowMs: 1350 },
      { x: 900, y: 350, w: 55, h: 108, requiredPads: ['B', 'C'], windowMs: 1350 },
    ],
    exitX: 938,
    exitY: 278,
    coop: false,
    sandReward: 87,
  },
  {
    id: 20,
    name: '第20室·双门',
    hint: `两扇门都要打开（各需在 1200ms 内满足）
门1需要 A+B，门2需要 B+C
利用 B 作为枢纽：A→B（回响A）→C（回响B）`,
    solution: 'A → B（回响A，门1开）→ C（回响B，门2开）→ 通过',
    pads: [
      { id: 'A', x: 543, y: 470, color: '#50e8a0' },
      { id: 'B', x: 175, y: 279, color: '#e0a030' },
      { id: 'C', x: 780, y: 421, color: '#c060ff' },
      { id: 'D', x: 602, y: 187, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 205, w: 55, h: 108, requiredPads: ['A', 'B'], windowMs: 1200 },
      { x: 900, y: 350, w: 55, h: 108, requiredPads: ['B', 'C'], windowMs: 1200 },
    ],
    exitX: 938,
    exitY: 278,
    coop: false,
    sandReward: 92,
  },
  {
    id: 21,
    name: '第21室·三鸣',
    hint: `门需要 A 和 C（950ms 内）
直接来回走不到，注意：踩了 B 会打断回响链
先踩 C（记住），再踩 A——回响触发 C`,
    solution: 'C → A（回响 C，A+C 同步激活）→ 门开（避开 B）',
    pads: [
      { id: 'A', x: 538, y: 148, color: '#50e8a0' },
      { id: 'C', x: 510, y: 486, color: '#c060ff' },
      { id: 'C', x: 566, y: 377, color: '#c060ff' },
      { id: 'D', x: 460, y: 340, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'C'], windowMs: 950 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 96,
  },
  {
    id: 22,
    name: '第22室·三鸣',
    hint: `门需要 A 和 C（880ms 内）
直接来回走不到，注意：踩了 B 会打断回响链
先踩 C（记住），再踩 A——回响触发 C`,
    solution: 'C → A（回响 C，A+C 同步激活）→ 门开（避开 B）',
    pads: [
      { id: 'A', x: 347, y: 310, color: '#50e8a0' },
      { id: 'C', x: 454, y: 104, color: '#c060ff' },
      { id: 'C', x: 535, y: 62, color: '#c060ff' },
      { id: 'D', x: 343, y: 147, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'C'], windowMs: 880 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 101,
  },
  {
    id: 23,
    name: '第23室·三鸣',
    hint: `门需要 A 和 C（820ms 内）
直接来回走不到，注意：踩了 B 会打断回响链
先踩 C（记住），再踩 A——回响触发 C`,
    solution: 'C → A（回响 C，A+C 同步激活）→ 门开（避开 B）',
    pads: [
      { id: 'A', x: 537, y: 352, color: '#50e8a0' },
      { id: 'C', x: 634, y: 483, color: '#c060ff' },
      { id: 'C', x: 278, y: 181, color: '#c060ff' },
      { id: 'D', x: 120, y: 439, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'C'], windowMs: 820 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 106,
  },
  {
    id: 24,
    name: '第24室·三鸣',
    hint: `门需要 A 和 C（760ms 内）
直接来回走不到，注意：踩了 B 会打断回响链
先踩 C（记住），再踩 A——回响触发 C`,
    solution: 'C → A（回响 C，A+C 同步激活）→ 门开（避开 B）',
    pads: [
      { id: 'A', x: 634, y: 192, color: '#50e8a0' },
      { id: 'C', x: 759, y: 442, color: '#c060ff' },
      { id: 'C', x: 707, y: 276, color: '#c060ff' },
      { id: 'D', x: 617, y: 297, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'C'], windowMs: 760 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 111,
  },
  {
    id: 25,
    name: '第25室·三鸣',
    hint: `门需要 A 和 C（700ms 内）
直接来回走不到，注意：踩了 B 会打断回响链
先踩 C（记住），再踩 A——回响触发 C`,
    solution: 'C → A（回响 C，A+C 同步激活）→ 门开（避开 B）',
    pads: [
      { id: 'A', x: 755, y: 353, color: '#50e8a0' },
      { id: 'C', x: 663, y: 448, color: '#c060ff' },
      { id: 'C', x: 812, y: 124, color: '#c060ff' },
      { id: 'D', x: 559, y: 356, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'C'], windowMs: 700 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 116,
  },
  {
    id: 26,
    name: '第26室·双门',
    hint: `两扇门都要打开（各需在 1050ms 内满足）
门1需要 A+B，门2需要 B+C
利用 B 作为枢纽：A→B（回响A）→C（回响B）`,
    solution: 'A → B（回响A，门1开）→ C（回响B，门2开）→ 通过',
    pads: [
      { id: 'A', x: 209, y: 361, color: '#50e8a0' },
      { id: 'B', x: 784, y: 313, color: '#e0a030' },
      { id: 'C', x: 372, y: 98, color: '#c060ff' },
      { id: 'D', x: 502, y: 397, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 205, w: 55, h: 108, requiredPads: ['A', 'B'], windowMs: 1050 },
      { x: 900, y: 350, w: 55, h: 108, requiredPads: ['B', 'C'], windowMs: 1050 },
    ],
    exitX: 938,
    exitY: 278,
    coop: false,
    sandReward: 120,
  },
  {
    id: 27,
    name: '第27室·双响',
    hint: `门需要 A 激活两次（间隔 ≤ 900ms）
踩 A（记住），快速走向 B 踩下——回响再次触发 A`,
    solution: 'A → B（回响 A → A 第二次激活）→ 门开',
    pads: [
      { id: 'A', x: 238, y: 124, color: '#50e8a0' },
      { id: 'B', x: 276, y: 247, color: '#e0a030' },
      { id: 'C', x: 89, y: 109, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'A'], windowMs: 900 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 126,
  },
  {
    id: 28,
    name: '第28室·双门',
    hint: `两扇门都要打开（各需在 800ms 内满足）
门1需要 A+B，门2需要 B+C
利用 B 作为枢纽：A→B（回响A）→C（回响B）`,
    solution: 'A → B（回响A，门1开）→ C（回响B，门2开）→ 通过',
    pads: [
      { id: 'A', x: 473, y: 92, color: '#50e8a0' },
      { id: 'B', x: 127, y: 481, color: '#e0a030' },
      { id: 'C', x: 430, y: 385, color: '#c060ff' },
      { id: 'D', x: 101, y: 68, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 205, w: 55, h: 108, requiredPads: ['A', 'B'], windowMs: 800 },
      { x: 900, y: 350, w: 55, h: 108, requiredPads: ['B', 'C'], windowMs: 800 },
    ],
    exitX: 938,
    exitY: 278,
    coop: false,
    sandReward: 132,
  },
  {
    id: 29,
    name: '第29室·双响',
    hint: `门需要 A 激活两次（间隔 ≤ 720ms）
踩 A（记住），快速走向 B 踩下——回响再次触发 A`,
    solution: 'A → B（回响 A → A 第二次激活）→ 门开',
    pads: [
      { id: 'A', x: 597, y: 298, color: '#50e8a0' },
      { id: 'B', x: 660, y: 371, color: '#e0a030' },
      { id: 'C', x: 249, y: 133, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'A'], windowMs: 720 },
    ],
    exitX: 938,
    exitY: 270,
    coop: false,
    sandReward: 138,
  },
  {
    id: 30,
    name: '第30室·双门',
    hint: `两扇门都要打开（各需在 650ms 内满足）
门1需要 A+B，门2需要 B+C
利用 B 作为枢纽：A→B（回响A）→C（回响B）`,
    solution: 'A → B（回响A，门1开）→ C（回响B，门2开）→ 通过',
    pads: [
      { id: 'A', x: 680, y: 321, color: '#50e8a0' },
      { id: 'B', x: 286, y: 277, color: '#e0a030' },
      { id: 'C', x: 713, y: 227, color: '#c060ff' },
      { id: 'D', x: 544, y: 361, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 205, w: 55, h: 108, requiredPads: ['A', 'B'], windowMs: 650 },
      { x: 900, y: 350, w: 55, h: 108, requiredPads: ['B', 'C'], windowMs: 650 },
    ],
    exitX: 938,
    exitY: 278,
    coop: false,
    sandReward: 145,
  },
  {
    id: 31,
    name: '双人第1室·镜像',
    hint: `两人分工：P1（WASD）前往 A，P2（方向键）前往 B
需在 600ms 内同时踩下——纯粹的眼神交流`,
    solution: 'P1:A 与 P2:B 同时踩下（600ms 内）→ 门开',
    pads: [
      { id: 'A', x: 210, y: 270, color: '#50e8a0' },
      { id: 'B', x: 680, y: 270, color: '#e0a030' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'B'], windowMs: 600 },
    ],
    exitX: 938,
    exitY: 270,
    coop: true,
    sandReward: 55,
  },
  {
    id: 32,
    name: '双人第2室·接力',
    hint: `两人各自负责一扇门（互相独立）
P1：踩 A → B（回响触发 A，门1）
P2：踩 C → D（回响触发 C，门2）`,
    solution: 'P1:A→B(回响A)=门1  P2:C→D(回响C)=门2  → 通过',
    pads: [
      { id: 'A', x: 155, y: 175, color: '#50e8a0' },
      { id: 'B', x: 380, y: 375, color: '#e0a030' },
      { id: 'C', x: 480, y: 175, color: '#c060ff' },
      { id: 'D', x: 680, y: 375, color: '#e06060' },
    ],
    doors: [
      { x: 900, y: 205, w: 55, h: 108, requiredPads: ['A', 'B'], windowMs: 1600 },
      { x: 900, y: 345, w: 55, h: 108, requiredPads: ['C', 'D'], windowMs: 1600 },
    ],
    exitX: 938,
    exitY: 275,
    coop: true,
    sandReward: 65,
  },
  {
    id: 33,
    name: '双人第3室·三角',
    hint: `门需要 A、B、C 全部在 1800ms 内激活
P1：踩 A → B（回响 A）
P2：在 P1 踩 B 的前后 1.8s 内踩 C`,
    solution: 'P1:A→B(回响A)  P2:恰当时机踩C  三者在1800ms内 → 门开',
    pads: [
      { id: 'A', x: 175, y: 200, color: '#50e8a0' },
      { id: 'B', x: 400, y: 380, color: '#e0a030' },
      { id: 'C', x: 650, y: 200, color: '#c060ff' },
    ],
    doors: [
      { x: 900, y: 270, w: 55, h: 160, requiredPads: ['A', 'B', 'C'], windowMs: 1800 },
    ],
    exitX: 938,
    exitY: 270,
    coop: true,
    sandReward: 75,
  },
  {
    id: 34,
    name: '双人第4室·回响交汇',
    hint: `两扇门各需某踏板激活两次（双响机制）
P1：踩 A（记住）→ 快速踩 E（回响触发 A 第二次）→ 门1
P2：踩 C（记住）→ 快速踩 F（回响触发 C 第二次）→ 门2
两人都要快！`,
    solution: 'P1:A→E(回响A,A×2)=门1  P2:C→F(回响C,C×2)=门2  → 通过',
    pads: [
      { id: 'A', x: 155, y: 160, color: '#50e8a0' },
      { id: 'E', x: 315, y: 160, color: '#40b8ff' },
      { id: 'C', x: 490, y: 390, color: '#c060ff' },
      { id: 'F', x: 660, y: 390, color: '#f0e040' },
    ],
    doors: [
      { x: 900, y: 185, w: 55, h: 108, requiredPads: ['A', 'A'], windowMs: 1100 },
      { x: 900, y: 360, w: 55, h: 108, requiredPads: ['C', 'C'], windowMs: 1100 },
    ],
    exitX: 938,
    exitY: 275,
    coop: true,
    sandReward: 90,
  },
  {
    id: 35,
    name: '双人第5室·时间悖论',
    hint: `终极挑战——窗口仅 650ms，任何失误都是全队重来
P1：踩 C（记住）→ 快速踩 A（回响 C）避开干扰踏板 E
P2：踩 D（记住）→ 快速踩 B（回响 D）避开干扰踏板 X
两人必须几乎同时完成各自序列`,
    solution: 'P1:C→A(回响C,避开E)=门1  P2:D→B(回响D,避开X)=门2  → 通关',
    pads: [
      { id: 'A', x: 200, y: 175, color: '#50e8a0' },
      { id: 'B', x: 610, y: 375, color: '#e0a030' },
      { id: 'C', x: 120, y: 375, color: '#c060ff' },
      { id: 'D', x: 700, y: 175, color: '#e06060' },
      { id: 'E', x: 155, y: 275, color: '#ff9090' },
      { id: 'X', x: 655, y: 275, color: '#90c0ff' },
    ],
    doors: [
      { x: 900, y: 185, w: 55, h: 108, requiredPads: ['A', 'C'], windowMs: 650 },
      { x: 900, y: 360, w: 55, h: 108, requiredPads: ['B', 'D'], windowMs: 650 },
    ],
    exitX: 938,
    exitY: 275,
    coop: true,
    sandReward: 120,
  }
]
