import { SkillType, SkillDefinition } from '../types/game.types'

export const SKILL_DEFINITIONS: Record<SkillType, SkillDefinition> = {
  burn_module: {
    id: 'burn_module',
    name: '灼烧模块',
    description: '将下一发射击变为火焰弹，命中后留下持续燃烧区域',
    element: 'fire',
    target: 'projectile',
    cooldown: 3000,
    echoDelay: 150,
    canBeEchoed: true,
    damage: 35,
    range: 400,
    duration: 3000,
    iconFrame: 0,
  },
  plague_module: {
    id: 'plague_module',
    name: '瘟疫模块',
    description: '将下一发射击变为毒雾弹，在目标位置生成持续毒云',
    element: 'poison',
    target: 'area',
    cooldown: 4000,
    echoDelay: 150,
    canBeEchoed: true,
    damage: 15,
    range: 350,
    duration: 5000,
    iconFrame: 1,
  },
  magnet_module: {
    id: 'magnet_module',
    name: '磁力模块',
    description: '将下一发射击变为磁力陷阱，将附近敌人拉向命中点',
    element: 'magnetic',
    target: 'area',
    cooldown: 5000,
    echoDelay: 200,
    canBeEchoed: true,
    damage: 20,
    range: 300,
    duration: 2000,
    iconFrame: 2,
  },
  teleport: {
    id: 'teleport',
    name: '瞬移',
    description: '瞬间跳跃到指针位置，留下残影迷惑敌人',
    element: 'void',
    target: 'self',
    cooldown: 6000,
    echoDelay: 300,
    canBeEchoed: true,
    range: 300,
    iconFrame: 3,
  },
  headshot: {
    id: 'headshot',
    name: '爆头弹',
    description: '发射高速穿甲弹，造成暴击伤害并短暂眩晕目标',
    element: 'physical',
    target: 'projectile',
    cooldown: 4500,
    echoDelay: 100,
    canBeEchoed: true,
    damage: 80,
    range: 500,
    iconFrame: 4,
  },
  toxic_fog: {
    id: 'toxic_fog',
    name: '毒雾',
    description: '在自身周围释放持续扩散的毒雾，持续造成中毒伤害',
    element: 'poison',
    target: 'area',
    cooldown: 7000,
    echoDelay: 200,
    canBeEchoed: true,
    damage: 10,
    range: 200,
    duration: 6000,
    iconFrame: 5,
  },
  shadow_clone: {
    id: 'shadow_clone',
    name: '分身',
    description: '在当前位置制造幻象分身，持续吸引敌人注意',
    element: 'void',
    target: 'self',
    cooldown: 8000,
    echoDelay: 500,
    canBeEchoed: true,
    duration: 4000,
    iconFrame: 6,
  },
  dash: {
    id: 'dash',
    name: '冲刺',
    description: '向鼠标方向高速冲刺，途中进入无敌状态',
    element: 'physical',
    target: 'self',
    cooldown: 3500,
    echoDelay: 100,
    canBeEchoed: true,
    range: 250,
    iconFrame: 7,
  },
  gravity_well: {
    id: 'gravity_well',
    name: '引力阱',
    description: '在目标点创造引力奇点，持续将范围内敌人拽向中心',
    element: 'magnetic',
    target: 'area',
    cooldown: 9000,
    echoDelay: 300,
    canBeEchoed: true,
    damage: 25,
    range: 400,
    duration: 3000,
    iconFrame: 8,
  },
  lightning_bolt: {
    id: 'lightning_bolt',
    name: '闪电弹',
    description: '发射闪电弹，命中后对附近敌人进行链式放电',
    element: 'electric',
    target: 'projectile',
    cooldown: 5500,
    echoDelay: 150,
    canBeEchoed: true,
    damage: 45,
    range: 450,
    iconFrame: 9,
    thirdEchoTransform: 'gravity_well',
  },
  cryo_field: {
    id: 'cryo_field',
    name: '冰晶域',
    description: '在落点区域生成冰晶地形，减缓并定身范围内敌人',
    element: 'cryo',
    target: 'area',
    cooldown: 7500,
    echoDelay: 250,
    canBeEchoed: true,
    damage: 20,
    range: 350,
    duration: 4000,
    iconFrame: 10,
  },
  void_pulse: {
    id: 'void_pulse',
    name: '虚空脉冲',
    description: '以自身为中心爆发虚空能量，击退并削弱所有周围敌人',
    element: 'void',
    target: 'area',
    cooldown: 10000,
    echoDelay: 400,
    canBeEchoed: false,
    damage: 60,
    range: 300,
    iconFrame: 11,
  },
}

// 可在深潜开始时选择的初始技能套装
export const STARTER_LOADOUTS: Record<string, { name: string; description: string; skills: SkillType[] }> = {
  flashSniper: {
    name: '闪狙刺客',
    description: '以瞬移结合爆头弹，一击脱离或处决敌人',
    skills: ['teleport', 'headshot', 'dash'],
  },
  emberWeaver: {
    name: '余烬编织者',
    description: '灼烧与毒雾的叠加，用时间换取指数伤害',
    skills: ['burn_module', 'toxic_fog', 'plague_module'],
  },
  timeDancer: {
    name: '时痕舞者',
    description: '分身与冲刺交织，让敌人永远无法锁定真身',
    skills: ['shadow_clone', 'dash', 'teleport'],
  },
}
